FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /Frontend

COPY Frontend.csproj .
RUN dotnet restore Frontend.csproj
COPY . .
RUN dotnet build Frontend.csproj -c Debug -o /app/build

FROM build AS publish
RUN dotnet publish Frontend.csproj -c Debug -o /app/publish

FROM mcr.microsoft.com/azure-functions/dotnet:4 AS final

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

WORKDIR /home/site/wwwroot

COPY --from=publish /app/publish .