FROM node:22-alpine AS build
WORKDIR /Editor
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=build /Editor/dist .
COPY nginx.conf /etc/nginx/nginx.conf
