FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /EditorNG
COPY EditorNG.csproj .
RUN dotnet restore EditorNG.csproj
COPY . .
RUN dotnet build EditorNG.csproj -c Debug -o /app/build

FROM build AS publish
RUN dotnet publish EditorNG.csproj -c Debug -o /app/publish

FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=publish /app/publish/wwwroot .
COPY nginx.conf /etc/nginx/nginx.conf